const employeData = [
  {
    "idUtilisateur": 2,
    "nomUtilisateur": "asasas",
    "prenomUtilisateur": "slasasl",
    "emailUtilisateur": "dsdksmdsk",
    "passwordUtilisateur": "kdssdk",
    "telephoneUtilisateur": "fack",
    "adresseUtilisateur": null,
    "datenaissanceUtilisateur": null,
    "cbyUtilisateur": null,
    "cdateUtilisateur": null,
    "ubyUtilisateur": null,
    "udateUtilisateur": null,
    "dbyUtilisateur": null,
    "ddateUtilisateur": null,
    "roleUtilisateur": null,
    "deletedUtilisateur": null
  },
  {
    "idUtilisateur": 3,
    "nomUtilisateur": "sdsdsd",
    "prenomUtilisateur": "kmdfek",
    "emailUtilisateur": "kdksdskssmk",
    "passwordUtilisateur": "mkmdkfdd",
    "telephoneUtilisateur": "skddskdm",
    "adresseUtilisateur": null,
    "datenaissanceUtilisateur": null,
    "cbyUtilisateur": null,
    "cdateUtilisateur": null,
    "ubyUtilisateur": null,
    "udateUtilisateur": null,
    "dbyUtilisateur": null,
    "ddateUtilisateur": null,
    "roleUtilisateur": null,
    "deletedUtilisateur": null
  },
  {
    "idUtilisateur": 4,
    "nomUtilisateur": "asasas",
    "prenomUtilisateur": "slasasl",
    "emailUtilisateur": "dsdksmdsk",
    "passwordUtilisateur": "kdssdk",
    "telephoneUtilisateur": "fack",
    "adresseUtilisateur": null,
    "datenaissanceUtilisateur": null,
    "cbyUtilisateur": null,
    "cdateUtilisateur": null,
    "ubyUtilisateur": null,
    "udateUtilisateur": null,
    "dbyUtilisateur": null,
    "ddateUtilisateur": null,
    "roleUtilisateur": null,
    "deletedUtilisateur": null
  },
  {
    "idUtilisateur": 5,
    "nomUtilisateur": "asasas",
    "prenomUtilisateur": "slasasl",
    "emailUtilisateur": "dsdksmdsk",
    "passwordUtilisateur": "kdssdk",
    "telephoneUtilisateur": "fack",
    "adresseUtilisateur": null,
    "datenaissanceUtilisateur": null,
    "cbyUtilisateur": null,
    "cdateUtilisateur": null,
    "ubyUtilisateur": null,
    "udateUtilisateur": null,
    "dbyUtilisateur": null,
    "ddateUtilisateur": null,
    "roleUtilisateur": null,
    "deletedUtilisateur": null
  },
  {
    "idUtilisateur": 6,
    "nomUtilisateur": "asasas",
    "prenomUtilisateur": "slasasl",
    "emailUtilisateur": "dsdksmdsk",
    "passwordUtilisateur": "kdssdk",
    "telephoneUtilisateur": "fack",
    "adresseUtilisateur": null,
    "datenaissanceUtilisateur": null,
    "cbyUtilisateur": null,
    "cdateUtilisateur": null,
    "ubyUtilisateur": null,
    "udateUtilisateur": null,
    "dbyUtilisateur": null,
    "ddateUtilisateur": null,
    "roleUtilisateur": null,
    "deletedUtilisateur": null
  },
  {
    "idUtilisateur": 8,
    "nomUtilisateur": "archane",
    "prenomUtilisateur": "zakaria",
    "emailUtilisateur": "zakariaarchane06@gmail.com",
    "passwordUtilisateur": "mdksdknf",
    "telephoneUtilisateur": "0550030303",
    "adresseUtilisateur": "28 rue badr bettana salé",
    "datenaissanceUtilisateur": "2000-03-16",
    "cbyUtilisateur": 3,
    "cdateUtilisateur": "2000-03-16",
    "ubyUtilisateur": 3,
    "udateUtilisateur": "2000-03-16",
    "dbyUtilisateur": 3,
    "ddateUtilisateur": "2000-03-16",
    "roleUtilisateur": 1,
    "deletedUtilisateur": 0
  },
  {
    "idUtilisateur": 9,
    "nomUtilisateur": "archane",
    "prenomUtilisateur": "zakaria",
    "emailUtilisateur": "zakariaarchane06@gmail.com",
    "passwordUtilisateur": "mdksdknf",
    "telephoneUtilisateur": "0550030303",
    "adresseUtilisateur": "28 rue badr bettana salé",
    "datenaissanceUtilisateur": "2000-03-16",
    "cbyUtilisateur": 3,
    "cdateUtilisateur": "2000-03-16",
    "ubyUtilisateur": 3,
    "udateUtilisateur": "2000-03-16",
    "dbyUtilisateur": 3,
    "ddateUtilisateur": "2000-03-16",
    "roleUtilisateur": 1,
    "deletedUtilisateur": 0
  },
  {
    "idUtilisateur": 698,
    "nomUtilisateur": "archane",
    "prenomUtilisateur": "zakaria",
    "emailUtilisateur": "zakariaarchane06@gmail.com",
    "passwordUtilisateur": "mdksdknf",
    "telephoneUtilisateur": "0550030303",
    "adresseUtilisateur": "28 rue badr bettana salé",
    "datenaissanceUtilisateur": "2000-03-16",
    "cbyUtilisateur": 3,
    "cdateUtilisateur": "2000-03-16",
    "ubyUtilisateur": 3,
    "udateUtilisateur": "2000-03-16",
    "dbyUtilisateur": 3,
    "ddateUtilisateur": "2000-03-16",
    "roleUtilisateur": 1,
    "deletedUtilisateur": 0
  },
  {
    "idUtilisateur": 699,
    "nomUtilisateur": "archane",
    "prenomUtilisateur": "zakaria",
    "emailUtilisateur": "zakariaarchane06@gmail.com",
    "passwordUtilisateur": "mdksdknf",
    "telephoneUtilisateur": "0550030303",
    "adresseUtilisateur": "28 rue badr bettana salé",
    "datenaissanceUtilisateur": "2000-03-16",
    "cbyUtilisateur": 3,
    "cdateUtilisateur": "2000-03-16",
    "ubyUtilisateur": 3,
    "udateUtilisateur": "2000-03-16",
    "dbyUtilisateur": 3,
    "ddateUtilisateur": "2000-03-16",
    "roleUtilisateur": 1,
    "deletedUtilisateur": 0
  },
  {
    "idUtilisateur": 700,
    "nomUtilisateur": "archane",
    "prenomUtilisateur": "zakaria",
    "emailUtilisateur": "zakariaarchane06@gmail.com",
    "passwordUtilisateur": "mdksdknf",
    "telephoneUtilisateur": "0550030303",
    "adresseUtilisateur": "28 rue badr bettana salé",
    "datenaissanceUtilisateur": "2000-03-16",
    "cbyUtilisateur": 3,
    "cdateUtilisateur": "2000-03-16",
    "ubyUtilisateur": 3,
    "udateUtilisateur": "2000-03-16",
    "dbyUtilisateur": 3,
    "ddateUtilisateur": "2000-03-16",
    "roleUtilisateur": 1,
    "deletedUtilisateur": 0
  },
  {
    "idUtilisateur": 701,
    "nomUtilisateur": "archane",
    "prenomUtilisateur": "zakaria",
    "emailUtilisateur": "zakariaarchane06@gmail.com",
    "passwordUtilisateur": "mdksdknf",
    "telephoneUtilisateur": "0550030303",
    "adresseUtilisateur": "28 rue badr bettana salé",
    "datenaissanceUtilisateur": "2000-03-16",
    "cbyUtilisateur": 3,
    "cdateUtilisateur": "2000-03-16",
    "ubyUtilisateur": 3,
    "udateUtilisateur": "2000-03-16",
    "dbyUtilisateur": 3,
    "ddateUtilisateur": "2000-03-16",
    "roleUtilisateur": 1,
    "deletedUtilisateur": 0
  }
]
  
  export default employeData
  
  